"""empty message

Revision ID: a2dc8d47ac59
Revises: cd7bef1ae813
Create Date: 2020-02-16 09:48:18.550779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import EmailType

# revision identifiers, used by Alembic.
revision = 'a2dc8d47ac59'
down_revision = 'cd7bef1ae813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=20),
               type_=EmailType(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=myapp.migration_types.EmailType(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
